= 基础语言特点
:scripts: cjk
:toc: left
:toclevels: 3
:toc-title: 目录
:numbered:
:sectnums:
:sectnum-depth: 3
:source-highlighter: coderay

== 基本概念

* 代码包被称为 crates

== 字面量(Literal)

* link:https://kaisery.github.io/trpl-zh-cn/appendix-01-keywords.html[关键字]
* 整数
+
[source,rust]
----
fn main() {
    // 十进制
    let decimal = 42;                       // 默认i32
    let unsigned1: u32 = 42;                // 显示声明类型
    let unsigned2 = 42u32;                  // 带类型后缀
    let large_number = 1_000_000;           // 下划线分隔，提高可读性

    let a = b'A';                           // Byte (单字节字符)(仅限于u8)

    // 二进制
    let binary1 = 0b1010;                   // 等于十进制 10
    let binary2 = 0b1111_0000;              // 下划线分隔，提高可读性

    // 八进制
    let octal = 0o755;                      // 等于十进制 493

    // 十六进制
    let hex1 = 0xFF;                         // 等于十进制 255
    let hex2 = 0xff;                         // 小写字母也可以
}
----
* 浮点
+
[source,rust]
----
fn main() {
    let float = 3.14159;                    // 默认f64
    let explicit_float: f32 = 2.71828f32;   // 显示声明类型
    let scientific = 1.23e-4;               // 科学计数法，等于 0.000123
}
----
* 布尔: `true` 和 `false`
* 字符: 用 `'` 包裹的单个unicode字符
+
[source,rust]
----
fn main() {
    let letter: char = 'A';
    let emoji: char = '😀';                 // Unicode 码点 U+1F600
    let escape = '\n';                      // 转义字符，换行符
}
----
* 字符串切片(`&str`): 不可变的字符串引用，用双引号 `"` 包裹
+
[source,rust]
----
fn main() {
    let greeting: &str = "Hello, world!";
    let multi_line = "
        这是一个
        多行字符串
    ";
}
----

** 原始字符串(`Raw String`): 避免转义，适合包含特殊字符的字符串
+
[source,rust]
----
fn main() {
    let raw_path = r"C:\Users\Admin\file.txt";                  // 无需转义反斜杠
    let html = r#"<div class="container">"#;                    // 使用 # 分隔符处理引号
    let tricky = r##"This string contains "#" characters!"##;   // 如果字符串中包含 "#，可以使用更多的 # 符号扩展定界符
}
----

*** 规则：
**** 使用 `r#"..."\#` 表示包含有一个 `#` 的字符串
**** 使用 `r#\#"..."#\#` 处理包含有两个 `#` 的字符串
**** 使用 `r\#\##"..."\###` 处理包含有三个 `#` 的字符串
**** 以此类推，# 的数量可以任意增加

== 变量

* 使用 `let` 关键字
* 可变的(`mut`)
** `mutable` 可变的，可以重新赋值或改变其内容，而 `immutable` 则相反
** 默认是不可变(`immutable`)的，使用 `mut` 来使一个变量可变
+
[source,rust]
----
fn main() {
    let apples = 5;         // 不可变
    apples = 6;             // 错误
    let mut bananas = 5;    // 可变
    bananas = 6 ;           // 没问题

    let mut s = String::from("hello");
    s.push_str(" world!");
    println!("{s}");
}
----
** 注意: `mut` 在引用中的意义有所不同，指的是引用的变量不能被重新赋值，但引用的变量所指向的值可以改变
* 遮蔽(`Shadowing`)
** 重复声明变量，后面的覆盖前面的
** 变量类型可以不相同

== 常量(constants)

* 使用 `const` 关键字而不是 `let`
* 必须声明值的类型
* 常量可以在任何作用域中声明，包括全局作用域
* 只能被设置为常量表达式，而不可以是其他任何只能在运行时计算出的值

== 数据类型

=== 标量(scalar)

==== 整型

[cols="2,1,1",options="header"]
|===
| 长度    | 有符号 | 无符号
| 8-bit  | i8    | u8
| 16-bit | i16   | u16
|32-bit  | i32   | u32
|64-bit  | i64   | u64
|128-bit | i128  | u128
|架构相关 | isize | usize
|===

[NOTE]
====
整型溢出

* `debug` 编译时，Rust 检查这类问题并使程序 `panic`
* `--release` 编译时，Rust 不会检测，当发生整型溢出时，会进行一种被称为二进制补码 wrapping（two’s complement wrapping）的操作，只保留未溢出的部分

显式地处理溢出

* 所有模式下都可以使用 `wrapping_*` 方法，如 `wrapping_add`
* 如果 `checked_*` 方法出现溢出，则返回 `None` 值
* 用 `overflowing_*` 方法返回值和一个布尔值，表示是否出现溢出
* 用 `saturating_*` 方法在值的最小值或最大值处进行饱和处理
====

==== 浮点型

* floating-point numbers
* `f32` 是单精度浮点数，`f64` 是双精度浮点数
* 浮点数采用 `IEEE-754` 标准表示

==== 布尔(bool)

* `true` 和 `false`

==== 字符类型(char)

* 大小为四个字节 (four bytes)
* 代表了一个 Unicode 标量值（Unicode Scalar Value）
* Unicode 标量值包含从 U+0000 到 U+D7FF 和 U+E000 到 U+10FFFF 在内的值

=== 复合类型(Compound types)

==== 元组(tuple)

[source,rust]
----
fn main() {
    let tup: (i32, f64, u8) = (500, 6.4, 1);
    let tup1 = (500, 6.4, 1);
    let (x, y, z) = tup1;                       // 解元组
    // 点号后跟值的索引
    let one = tup1.0;                           // 500
    let two = tup1.1;                           // 6.4
    let three = tup1.2;                         // 1
}
----

* 元组是一个将多个不同类型的值组合进一个复合类型的主要方式
* 元组长度固定：一旦声明，其长度不会增大或缩小
* 元组中的每一个位置都有一个类型，而且这些不同值的类型也不必是相同的
* 可以使用 `.` 后跟值的索引来直接访问所需的元组元素(第一个索引值是 `0`)
* 可以使用元组来返回多个值
+
[source,rust]
----
fn main() {
    let s1 = String::from("hello");

    let (s2, len) = calculate_length(s1);

    println!("The length of '{s2}' is {len}.");
}

fn calculate_length(s: String) -> (String, usize) {
    let length = s.len(); // len() 返回字符串的长度

    (s, length)
}
----

==== 数组(array)

* 每个元素的类型必须相同
* 长度是固定的
* 在栈（stack）而不是堆（heap）上为数据分配空间
* 可以这样声明类型: 在方括号中包含每个元素的类型，后跟分号，再后跟数组元素的数量
* 可以通过在方括号中指定初始值加分号再加元素个数来创建一个每个元素都为相同值的数组
* 可以使用索引来访问数组的元素

[source,rust]
----
fn main() {
    let a = [1, 2, 3, 4, 5];
    let a: [i32; 5] = [1, 2, 3, 4, 5];
    let a = [3; 5];                             // [3,3,3,3,3]
    let first = a[0];
    let second = a[1];
}
----

=== 字符串

* `&str` 是不可变的
* `String` 是标准库提供的类型，用来管理被分配到堆上的数据，所以能够存储在编译时未知大小的文本

=== Result类型

* `Result` 是一种枚举类型，通常也写作 `enum`，它可以是多种可能状态中的一个
* 我们把每种可能的状态称为一种 枚举成员（`variant`）
* `Result` 的成员是 `Ok` 和 `Err`
** `Ok` 成员表示操作成功，内部包含成功时产生的值
** `Err` 成员则意味着操作失败，并且 `Err` 中包含有关操作失败的原因或方式的信息
* `expect` 方法
** 如果 Result 实例的值是 `Err`，`expect` 会导致程序崩溃，并输出传递给 `expect` 的参数
** 如果 Result 实例的值是 `Ok`，`expect` 会获取 `Ok` 中的值并原样返回

=== vector

* 标准库提供的一个允许增长和缩小长度的类似数组的集合类型

== 表达式

* 范围表达式使用了 start..=end 这样的形式，它对上下边界均为闭区间
* 与语句区别
+
[source,rust]
----
fn main() {
    let y = {
        let x = 3;      // 语句
        x + 1           // 表达式
    };

    println!("The value of y is: {y}");
}
----

** 语句（Statements）是执行一些操作但不返回值的指令
** 表达式（Expressions）计算并产生一个值

== 函数

* `::` 表示是类的函数，而 `.` 表示是对象的函数
* 形参(`parameters`)，实参(`arguments`)
* 具有返回值的函数
+
[source,rust]
----
fn five() -> i32 {
    5
}
----

** 要在箭头（->）后声明返回值的类型
** 函数的返回值等同于函数体最后一个表达式的值
** 使用 `return` 关键字和指定值，可从函数中提前返回

== 注释

=== 普通注释(//)

[source,rust]
----
// hello, world
----

=== 文档注释(///)

[source,rust]
----
/// Adds one to the number given.
///
/// # Examples
///
/// ```rust
/// let arg = 5;
/// let answer = my_crate::add_one(arg);
///
/// assert_eq!(6, answer);
/// ```
pub fn add_one(x: i32) -> i32 {
    x + 1
}
----

* 支持 `Markdown` 注解
* 常用（文档注释）部分
** Panics：可能会 panic!
的场景
** Errors：如果这个函数返回 Result，可能会出现何种错误以及什么情况会造成这些错误
** Safety：如果这个函数使用 unsafe 代码，这一部分应该会涉及到期望函数调用者支持的确保 unsafe 块中代码正常工作的不变条件（invariants）
* 测试文档注释中的代码: `cargo test`

=== 包含注释的项(//!)

* `//!` 会将文档添加到包含注释的项，而不是在项后跟着注释
* 通常用来在根Crate或Module里边记录整个Crate或Module的注释
* 请注意，一般以 `//!` 开头的最后一行之后不应该紧跟着任何代码，而是空一行接着 `///` 注释来开始实际的代码
